package com.sber.sberbot.models.enums;

public enum State {
    FREE,
    WAITING_USERNAME_FOR_ADD_ADMIN,
    WAITING_ID_FOR_USERS_MESSAGE,
    WAITING_ID_FOR_CHANGE_USERS_STATUS, WAITING_ID_FOR_DELETE_ADMIN
}
